<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Saran" name="com.sra.qa.Testcases.mutipleDatadriver" tests="10" failures="8" timestamp="2021-06-26T16:47:46 IST" time="217.582" errors="0">
  <testcase name="login" time="7.862" classname="com.sra.qa.Testcases.mutipleDatadriver"/>
  <system-out/>
  <testcase name="selectcompany" time="33.133" classname="com.sra.qa.Testcases.mutipleDatadriver"/>
  <system-out/>
  <testcase name="newexcelUpload" time="21.891" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [TimeChimp] but found [Plant Health Cure],
	expected [8 feb. 2021] but found [12-03-2021],
	expected [67,19] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl855621102b01] but found [nl807617350b01],
	expected [188759(0085) - Afschrijving Website] but found [0100 - Goodwill],
	expected [11,66] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TimeChimp] but found [Plant Health Cure],
expected [8 feb. 2021] but found [12-03-2021],
expected [67,19] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl855621102b01] but found [nl807617350b01],
expected [188759(0085) - Afschrijving Website] but found [0100 - Goodwill],
expected [11,66] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="21.429" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Loonservicebureau Robest] but found [Plant Health Cure],
	expected [23-09-2020] but found [12-03-2021],
	expected [34,30] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl860845813b01] but found [nl807617350b01],
	expected [188999(4850) - Administratiekosten] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Loonservicebureau Robest] but found [Plant Health Cure],
expected [23-09-2020] but found [12-03-2021],
expected [34,30] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl860845813b01] but found [nl807617350b01],
expected [188999(4850) - Administratiekosten] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="21.972" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Bloemisterij Pasmans] but found [Plant Health Cure],
	expected [31-08-2020] but found [12-03-2021],
	expected [186,98] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl805358328b01] but found [nl807617350b01],
	expected [4203040(4330) - Relatiegeschenken] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Bloemisterij Pasmans] but found [Plant Health Cure],
expected [31-08-2020] but found [12-03-2021],
expected [186,98] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl805358328b01] but found [nl807617350b01],
expected [4203040(4330) - Relatiegeschenken] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="20.383" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Lyreco Nederland B.V.] but found [Plant Health Cure],
	expected [31-07-2020] but found [12-03-2021],
	expected [88,21] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl00l427507b0l] but found [nl807617350b01],
	expected [188989(4800) - Kantoorartikelen] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Lyreco Nederland B.V.] but found [Plant Health Cure],
expected [31-07-2020] but found [12-03-2021],
expected [88,21] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl00l427507b0l] but found [nl807617350b01],
expected [188989(4800) - Kantoorartikelen] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="22.615" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Kamer van Koophandel] but found [Plant Health Cure],
	expected [31-08-2020] but found [12-03-2021],
	expected [14,15] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl823807071b01] but found [nl807617350b01],
	expected [188965(4599) - Overige kantoorkosten] but found [0820 - Onderhandse lening H.M.M. / P.C.M. Lauwerijssen],
	expected [0,00] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Kamer van Koophandel] but found [Plant Health Cure],
expected [31-08-2020] but found [12-03-2021],
expected [14,15] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl823807071b01] but found [nl807617350b01],
expected [188965(4599) - Overige kantoorkosten] but found [0820 - Onderhandse lening H.M.M. / P.C.M. Lauwerijssen],
expected [0,00] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="24.702" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Lindenhaeghe Opleidingen B.V.] but found [Plant Health Cure],
	expected [21-09-2020] but found [12-03-2021],
	expected [8,95] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl853877889b01] but found [nl807617350b01],
	expected [4012190(4099) - Overige personeelskosten] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Lindenhaeghe Opleidingen B.V.] but found [Plant Health Cure],
expected [21-09-2020] but found [12-03-2021],
expected [8,95] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl853877889b01] but found [nl807617350b01],
expected [4012190(4099) - Overige personeelskosten] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="21.339" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Restaurant Welp B.V.] but found [Plant Health Cure],
	expected [28-09-2020] but found [12-03-2021],
	expected [300,06] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl857701460b01] but found [nl807617350b01],
	expected [188947(4310) - Donaties en sponsoring] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Restaurant Welp B.V.] but found [Plant Health Cure],
expected [28-09-2020] but found [12-03-2021],
expected [300,06] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl857701460b01] but found [nl807617350b01],
expected [188947(4310) - Donaties en sponsoring] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
  <testcase name="newexcelUpload" time="22.256" classname="com.sra.qa.Testcases.mutipleDatadriver">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [BMW Financial Services] but found [Plant Health Cure],
	expected [12-Jan-2020] but found [12-03-2021],
	expected [404,72] but found [225,51],
	expected [nl26abna0444007601] but found [],
	expected [nl801980926b01] but found [nl807617350b01],
	expected [188966(4600) - Leasekosten auto] but found [0100 - Goodwill],
	expected [0,00] but found [39,14]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [BMW Financial Services] but found [Plant Health Cure],
expected [12-Jan-2020] but found [12-03-2021],
expected [404,72] but found [225,51],
expected [nl26abna0444007601] but found [],
expected [nl801980926b01] but found [nl807617350b01],
expected [188966(4600) - Leasekosten auto] but found [0100 - Goodwill],
expected [0,00] but found [39,14]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.sra.qa.TC.Ocrfileupload.excelUpload(Ocrfileupload.java:394)
at com.sra.qa.Testcases.mutipleDatadriver.newexcelUpload(mutipleDatadriver.java:209)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- newexcelUpload -->
  <system-out/>
</testsuite> <!-- com.sra.qa.Testcases.mutipleDatadriver -->
